/*
 * I, Haniyeh Jalayeri, 000965841 certify that this material is my original work.  
 * No other person's work has been used without due acknowledgement.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab5bS2541
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Represents a Doctor Who companion, including their name,
    /// actor, and links to the Doctor and Episode they appear with.
    /// </summary>
    public partial class COMPANION
    {
        /// <summary>
        /// Name of the companion character.
        /// </summary>
        public string NAME { get; set; }

        /// <summary>
        /// Actor who played the companion.
        /// </summary>
        public string ACTOR { get; set; }

        /// <summary>
        /// Foreign key ID of the Doctor associated with this companion.
        /// </summary>
        public int DOCTORID { get; set; }

        /// <summary>
        /// Foreign key ID of the story/episode the companion appears in.
        /// </summary>
        public string STORYID { get; set; }

        /// <summary>
        /// Navigation property to the related Doctor.
        /// </summary>
        public virtual DOCTOR DOCTOR { get; set; }

        /// <summary>
        /// Navigation property to the related Episode.
        /// </summary>
        public virtual EPISODE EPISODE { get; set; }
    }
}

