//------------------------------------------------------------------------------
/*
 * I, Haniyeh Jalayeri, 000965841 certify that this material is my original work.  
 * No other person's work has been used without due acknowledgement.
 */
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab5bS2541
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Represents a Doctor in the Doctor Who database.
    /// Includes basic info, photo, companions, and a related episode.
    /// </summary>
    public partial class DOCTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCTOR()
        {
            this.COMPANIONs = new HashSet<COMPANION>();
        }

        /// <summary>
        /// Primary key for the Doctor record.
        /// </summary>
        public int DOCTORID { get; set; }

        /// <summary>
        /// Actor who played this Doctor.
        /// </summary>
        public string ACTOR { get; set; }

        /// <summary>
        /// The Doctor’s series/ordinal number 
        /// </summary>
        public int SERIES { get; set; }

        /// <summary>
        /// Age of the actor 
        /// </summary>
        public int AGE { get; set; }

        /// <summary>
        /// Debut information 
        /// </summary>
        public string DEBUT { get; set; }

        /// <summary>
        /// Photo of the Doctor as a byte array.
        /// </summary>
        public byte[] PICTURE { get; set; }

        /// <summary>
        /// Companions associated with this Doctor.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPANION> COMPANIONs { get; set; }

        /// <summary>
        /// Related episode record
        /// </summary>
        public virtual EPISODE EPISODE { get; set; }
    }
}
