//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab5bS2541
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class COMP10204W25_LAB5Entities : DbContext
    {
        public COMP10204W25_LAB5Entities()
            : base("name=COMP10204W25_LAB5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DOCTOR> DOCTORs { get; set; }
        public virtual DbSet<EPISODE> EPISODEs { get; set; }
        public virtual DbSet<COMPANION> COMPANIONs { get; set; }
    }
}
