/*
 * I, Haniyeh Jalayeri, 000965841 certify that this material is my original work.  
 * No other person's work has been used without due acknowledgement.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab5bS2541
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// Represents an episode of Doctor Who, including its story ID, season,
    /// title, and the Doctors and Companions that appear in it.
    /// </summary>
    public partial class EPISODE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EPISODE()
        {
            this.DOCTORs = new HashSet<DOCTOR>();
            this.COMPANIONs = new HashSet<COMPANION>();
        }
        /// <summary>
        /// property for STORYID
        /// </summary>
        public string STORYID { get; set; }
        /// <summary>
        /// property for SEASON
        /// </summary>
        public int SEASON { get; set; }
        /// <summary>
        /// property for SEASONYEAR
        /// </summary>
        public int SEASONYEAR { get; set; }
        /// <summary>
        /// property for TITLE
        /// </summary>
        public string TITLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        /// <summary>
        /// Collection of Doctors appearing in this episode
        /// </summary>
        public virtual ICollection<DOCTOR> DOCTORs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        /// <summary>
        /// Collection of Companions appearing in this episode
        /// </summary>
        public virtual ICollection<COMPANION> COMPANIONs { get; set; }
    }
}
